### ISSUE TITLE
HP Procurve exiting sub-config for vlan

### ISSUE THREAD

**Issue by nexty5870** [ktbyers/netmiko#1189] opened 2019-04-26 21:13 UTC
hey guys, 

I'm sure there is a way to avoid this issue, I've been working on a script allowing user to configure a vlan base on a base vlan, the code return the right vlan however netmiko seems to get lost during the vlan configuration, here is the code for reference:

```
    u = raw_input('Vlan to lookup: ')
    u2 = raw_input('New vlan ID: ')
    u3 = raw_input('New vlan name: ')    
    lookup_vlan = conn.send_command('show running-config vlan '+ u)
    m1 = re.search(r'   tagged (\d+-?\d+)', lookup_vlan)
    conn.config_mode()
    conn.send_config_set('vlan '+ u2+ ' name '+ u3)
    conn.send_config_set('name '+ u3)
    conn.send_config_set('tagged '+ m1.group(1))
    conn.send_config_set('no ip address')
    print(m1.group(1))
    conn.exit_config_mode()
```
when running the code manually, I've notice that it get stuck at the "name" and or "tagged" command see bellow

>>> conn.config_mode()
u'\x1b[24;13Hconfig ter\x1b[24;13H\x1b[?25h\x1b[24;23H\x1b[24;23Hm\x1b[24;23H\x1b[?25h\x1b[24;24H\x1b[24;0H\x1bE\x1b[24;1H\x1b[24;24H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[1;24r\x1b[24;1H\x1b[24;1H\x1b[2K\x1b[24;1H\x1b[?25h\x1b[24;1H\x1b[24;1HTestSwitch(config)# \x1b[24;1H\x1b[24;21H\x1b[24;1H\x1b[?25h\x1b[24;21H'
>>> conn.send_config_set('vlan '+ u2)
u'vlan 113\nTestSwitch(vlan-113)# end\nTestSwitch# '
>>> conn.send_config_set('name '+ u3)
u'config term\nTestSwitch(config)# name test\nInvalid input: name\nTestSwitch(config)# end\nTestSwitch# '

as you see on the output, Netmiko goes to the config mode for that vlan 113, but send a end, meaning that the name or tagged/untagged setting cannot be perform

is there a possibility to handle that via netmiko? 

I'm running this on a hp_procurve switch

maybe I should use something different then send_config_set?

**Comment by carlniger** [comment] 2019-04-29 15:55
@nexty5870 please try sending your configs as a list. 

```
configs_to_send = [f'vlan  {u2} name {u3}',  f'name  {u3}', f'tagged {m1.group(1)}']
conn.send_config_set(configs_to_send)
```

the "send_config_set" function will automatically enter/exit config mode, so by sending commands one at a time its exiting config mode and thus giving you "invalid input" that you see in your output

**Comment by carlniger** [comment] 2019-05-13 21:53
I'm going to close this since its not a bug/issue/feature request. Feel free to join the Pynet slack community here where you can find a dedicated netmiko channel for questions/comments/etc.

**Closed by carlniger** 2019-05-13 21:53 UTC
Labels: pending_close
