### ISSUE TITLE
Error in wrong username

### ISSUE THREAD

**Issue by agpol07** [ktbyers/netmiko#1282] opened 2019-07-12 05:49 UTC
Hi,

I'm trying to simulate a case where the user enters wrong username, when trying to connect to a Cisco VGW. 

from netmiko import ConnectHandler
from paramiko.ssh_exception import SSHException
import getpass

try:
    username = input('insert your USERNAME: ')
    password = getpass.getpass('Insert your PASSWORD: ')
    iosv_l2= { 
            'device_type': 'cisco_ios',
            'ip': 'VGW_IP',
            'username': username,
            'password': password
    }
    net_connect = ConnectHandler(**iosv_l2)  
except SSHException:
    print('Ivalid Credentials')    

When i enter an empty Username it works fine:

insert your USERNAME:
Insert your PASSWORD:

Connecting to VGW...
Ivalid Credentials

But in case i enter a wrong username i get this:

insert your USERNAME: sdfh
Insert your PASSWORD:

Connecting to VGW...
Exception: Illegal info request from server
Traceback (most recent call last):
  File "C:\......Local\Programs\Python\Python37\lib\site-packages\paramiko\transport.py", line 2109, in run
    handler(self.auth_handler, m)
  File "C:\.........\Local\Programs\Python\Python37\lib\site-packages\paramiko\auth_handler.py", line 661, in _parse_userauth_info_request
    raise SSHException("Illegal info request from server")
paramiko.ssh_exception.SSHException: Illegal info request from server

Ivalid Credentials

**Comment by agpol07** [comment] 2019-07-12 07:20
update...

The wrong behavior comes up only when you enter a wrong username and an empty password.
If both are empty, or both wrong, or username empty and password wrong, it works fine.

**Comment by agpol07** [comment] 2019-07-12 07:25
and one last conclusion..
when device_type is "cisco_ios_telnet", everything works fine..

**Comment by carlniger** [comment] 2019-07-15 16:53
What is the issue you're facing here? 

With SSH (no "_telnet" in the device type name) -- paramiko will fail if there is no password word SSH key provided (no authentication methods available). With a bad username and a empty string as a password I just see "Authentication failed" which is what I would expect. So it seems like this is all working as it should unless I'm missing something?

**Comment by agpol07** [comment] 2019-07-15 17:16
The issue is that it prints this, too

Exception: Illegal info request from server
Traceback (most recent call last):
File "C:......Local\Programs\Python\Python37\lib\site-packages\paramiko\transport.py", line 2109, in run
handler(self.auth_handler, m)
File "C:.........\Local\Programs\Python\Python37\lib\site-packages\paramiko\auth_handler.py", line 661, in _parse_userauth_info_request
raise SSHException("Illegal info request from server")
paramiko.ssh_exception.SSHException: Illegal info request from server

**Comment by carlniger** [comment] 2019-07-15 23:28
I can't reproduce this (with SSH on an IOS-XE box) since I just get the appropriate auth fail exceptions. Does the platform not have SSH enabled (asking since you mentioned that telnet works)? Not sure why that try/except isn't catching the exception, but hard to tell w/ what's in this thread. You could try to have a generic except to see if that actually catches the exception and behaves how you want.

**Comment by agpol07** [comment] 2019-07-16 04:33
If you read carefully, you'll see that I mention, that the extra lines are printed only when i enter a wrong username and an empty password.
If both are empty, or both wrong, or username empty and password wrong, it works fine. It catches the exception but it print out some extra lines that I don't want to. If I try to reproduce to another iOS ex iOS_telnet or nx_ios, at other routers not the same, it doesn't print out these extra line at any of the scenarios. 

I hope I made my self clear..

**Comment by carlniger** [comment] 2019-07-16 14:42
As I said, you can try to catch a generic exception and print your own message or whatever you prefer. Given the exception it still sounds like you're trying to SSH to a device that doesn't have SSH enabled (hence why it works when switching the connect handler to telnet). In any case, this isn't a netmiko bug/enhancement so I'm going to close this. 

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.

**Closed by carlniger** 2019-07-16 14:42 UTC
