### ISSUE TITLE
Netmiko not installed properly on Windows

### ISSUE THREAD

**Issue by libaax** [ktbyers/netmiko#1886] opened 2020-08-18 02:36 UTC
PS C:\users\libaa\PycharmProjects\myproject> python3 .\netmiko_connect_run.py
Traceback (most recent call last):
  File ".\netmiko_connect_run.py", line 1, in <module>
    from netmiko import ConnectHandler
  File "C:\Users\libaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\netmiko\__init__.py", line 7, in <module>
    from netmiko.ssh_dispatcher import ConnectHandler
  File "C:\Users\libaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\netmiko\ssh_dispatcher.py", line 2, in <module>
    from netmiko.a10 import A10SSH
  File "C:\Users\libaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\netmiko\a10\__init__.py", line 1, in <module>
    from netmiko.a10.a10_ssh import A10SSH
  File "C:\Users\libaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\netmiko\a10\a10_ssh.py", line 3, in <module>
    from netmiko.cisco_base_connection import CiscoSSHConnection
using win10/vmware WS Pro/Gns3/GNS3VM python3.8/pycharm/paramiko/netmiko with ios/lou/qemu appliances. I got stuck with netmiko execution...keeps failing see below: any assistance will be greately appriciated! 👍 

Error shown with simple ConnectHandler script. I'm able to ping/ssh and telnet to the target. and all requirements were met including SSH 

File "C:\Users\libaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\netmiko\cisco_base_connection.py", line 2, in <module>
    from netmiko.base_connection import BaseConnection
  File "C:\Users\libaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\netmiko\base_connection.py", line 27, in <module>
    from netmiko.utilities import (
  File "C:\Users\libaa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\netmiko\utilities.py", line 8, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'; 'serial' is not a package

**Comment by libaax** [comment] 2020-08-18 02:41
from netmiko import ConnectHandler
cisco_device = {
       'device_type': 'cisco_ios',     #device type from https://github.com/ktbyers/netmiko/blob/master/netmiko/ssh_dispatcher.py
       'host': '10.1.1.10',
       'username': 'u1',
       'password': 'cisco',
       'port': 22,             # optional, default 22
       'secret': 'cisco',      # this is the enable password
       'verbose': True         # optional, default False
       }
connection = ConnectHandler(**cisco_device)

# getting the router's prompt
prompt = connection.find_prompt()
if '>' in prompt:
       connection.enable()   # entering the enable mode

output = connection.send_command('sh run')
print(output)

if not connection.check_config_mode(): # returns True if it's already in the global config mode
       connection.config_mode()  # entering the global config mode

# print(connection.check_config_mode())
connection.send_command('username u3 secret cisco')

connection.exit_config_mode()  # exiting the global config mode
print(connection.check_config_mode())

print('Closing connection')
connection.disconnect()

**Comment by libaax** [comment] 2020-08-18 03:14
PS C:\WINDOWS\system32> python -m serial.tools.list_ports
no ports found

Above is possibly my main issue. module doesn't return ports.

**Comment by ktbyers** [comment] 2020-08-18 03:52
How did you install Netmiko? 

Your installation looks incorrect in that you did not install the pyserial library which should have been installed automatically with Netmiko.

https://github.com/ktbyers/netmiko/blob/develop/setup.py#L52

**Comment by libaax** [comment] 2020-08-18 03:56
Thanks for your attentions..I really much appreciate it.
Several ways:

  1.  In pythcharm file>setting>project Interpreter> +>netmiko > install package
  2.  In PowerShell(administrator) pip install netmiko
BTW: paramiko is working fine.  Only netmiko is giving me headaches. Pleas

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ktbyers** [comment] 2020-08-18 15:08
This:

`pip install netmiko`

Should have installed 'pyserial'


What happens if you do an

```
import serial
```

Regards, Kirk

**Comment by libaax** [comment] 2020-08-18 15:19
I tried pip install netmiko, pip install pyserial, pip install esptools
I don’t remember doing import serial. After several days for utter frustration and after having the same result with visual studio, anaconda, spyder, and also jupyter. I decided to remove everything and instead install ubuntu on VMware. Next few days, I will start from scratch and buildup management desktop using ubuntu. Hopefully that will allow me to finally complete my network automation labs such as paramiko, netmiko, napalm and ansible. Thanks for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ktbyers** [comment] 2020-08-18 15:25
One frequent cause of this issue (especially with IDEs) is the Python that the IDE is using is not the Python where a given thing was installed.

So you might want to use `pip freeze` or `pip list` and verify that both netmiko and `serial` are installed in the Python that is being used by your IDE (or directly run a Python script outside of your IDE and verify it is working).

**Comment by libaax** [comment] 2020-08-18 15:31
I didn’t know that commands you mensioned below…But, I used the following to verify they were installed
Pip show netmiko
Pip show esptool
Pip show pyserial
The only thing that returned a concern was the command below

PS C:\WINDOWS\system32> python -m serial.tools.list_ports
no ports found

Above is possibly my main issue. module doesn't return ports as it should.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ktbyers** [comment] 2020-08-18 15:39
This error here:

```
import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial.tools'; 'serial' is not a package
```

Makes me thing `pyserial` is not installed or you have something else named `serial.py` that is conflicting with the standard library. 

This also makes me thing the problem is not due to this:

```
PS C:\WINDOWS\system32> python -m serial.tools.list_ports
no ports found
```

Note, your original error is different than the above and is saying "ModuleNotFoundError". I think not finding in any serial ports would not cause the problem you reported initially.

Also note, it looks like you might be switching the Python you are using. In your first output you did:

```
python3 .\netmiko_connect_run.py
```

Then in later output you just did:

```
python -m serial.tools.list_ports
```

Those could easily be different Python's with different things installed.

Also with 'pip' you probably should be verifying it using the following `python -m pip list` (in other words, force the PIP output to be associated with the `python` that you care about by using the `-m pip` option to python.

Anyways, I am pretty sure this is not your issue (at least as originally reported):


```
PS C:\WINDOWS\system32> python -m serial.tools.list_ports
no ports found
```

Regards, Kirk

**Comment by libaax** [comment] 2020-08-18 16:26
Could it be that because I didn’t add target devices ip addresses to the hosts file, netmiko would freak-out? Otherwise, I guess there are multiple installations of modules conflicting here. I may have to dig around and remove all traces of python and clean registry, then reinstall.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ktbyers** [comment] 2020-08-18 16:31
I definitely think it is a Python environment issue on your side (libraries installed, python/pip mismatch, conflicting serial.py that you created, or something similar).

I am not sure about this but would put it higher than 75% chance.

**Comment by libaax** [comment] 2020-08-18 16:36
I hate to wipe out the system. But, let me manually try and uninstall, and search for libraries using keywords and destroy them. Please suggest a good registry cleaner as well. I shall work on that next couple of days.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ktbyers** [comment] 2020-08-18 16:39
@libaax You should be able to just create a new Python virtual environment and test using that. No need to start with a new system.

**Comment by ktbyers** [comment] 2020-08-20 03:23
@libaax What happens when you:

```
import serial
```

In your new environment?

**Comment by ktbyers** [comment] 2020-08-23 17:32
I am going to close this issue; I am pretty convinced that is a PyCharm/environment issue on your side and not really a Netmiko issue.

**Closed by ktbyers** 2020-08-23 17:32 UTC
