### ISSUE TITLE
Updating local accounts password

### ISSUE THREAD

**Issue by kabaga** [ktbyers/netmiko#977] opened 2018-10-13 00:32 UTC
Hi,

I am trying to update the local account on all of my Juniper and some Cisco devices, but I could not get this to work. I did not get an error and I got the print at the end of the for loop. When I logged in to any of the device 10.1.1.1, the account I was using for testing, the password did not change.

```python
from netmiko import ConnectHandler
import getpass

junos_list = ['10.1.1.1']

username = input("Username : ")
password = getpass.getpass("Password : ")


print("Enter the account you would like to update")
local_user = input("Local account username : ")
new_password = input ("Enter the new password : ")


#Juniper device root account
if (local_username == "root") and (username == "admin"):   
    for i in junos_list:
        userssh = ConnectHandler(device_type='juniper_junos', ip=i, port=22, username=username, password=password)
        root_login_cred = ('set system root-authentication plain-text-password')
        root_login_passwd = (new_password)
        root_login_confirm_passwd = (new_password)
        userssh.send_config_set(root_login_cred)
        userssh.send_config_set(root_login_passwd)
        userssh.send_config_set(root_login_confirm_passwd)
        userssh.disconnect()
        print("\n\tThe root password has been updated for", i)
else:
    for la in junos_list:
        userssh = ConnectHandler(device_type='juniper_junos', ip=la, port=22, username=username, password=password)
        la_login_cred = ('set system login user ' + local_user +  ' authentication plain-text-password')
        la_login_passwd = (new_password)
        la_login_confirm_passwd = (new_password)
        config_commands = ([la_login_cred, la_login_passwd, la_login_passwd])
        userssh.send_config_set(config_commands)
        userssh.send_config_set(la_login_passwd)
        userssh.send_config_set(la_login_confirm_passwd)
        userssh.commit()
        userssh.disconnect()
        print("\n\tThe password has been updated for node", la)
        
```

**Comment by ktbyers** [comment] 2018-10-26 17:52
In the `root` and `admin` section, you don't execute a `commit`? 

What was the username that failed?


Kirk

**Comment by carlniger** [comment] 2019-05-24 17:30
Going to close this. Please re-open if this is still an issue.

**Closed by carlniger** 2019-05-24 17:30 UTC

**Comment by dasiimwe** [comment] 2021-01-15 19:22
please reopen this. The problem is that on juniper 'set system root-authentication plain-text-password' prompts the user to enter the new password and .send_config_set doesn't know how to handle this. 

.send_config_set doesn't know how to handle the 'New Password' prompt

```
user@junos> configure 
Entering configuration mode

[edit]
user@junos# set system login user username_here authentication plain-text-password 
New password:
```

```
junos_connection.send_config_set('set system login user username_here authentication plain-text-password')

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/paramiko/channel.py", line 699, in recv
    out = self.in_buffer.read(nbytes, self.timeout)
  File "/usr/local/lib/python3.8/dist-packages/paramiko/buffered_pipe.py", line 164, in read
    raise PipeTimeout()
paramiko.buffered_pipe.PipeTimeout
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 1868, in send_config_set
    new_output = self.read_until_pattern(pattern=pattern)
  File "/home/user/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 646, in read_until_pattern
    return self._read_channel_expect(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/netmiko/base_connection.py", line 579, in _read_channel_expect
    raise NetmikoTimeoutException(
netmiko.ssh_exception.NetmikoTimeoutException: Timed-out reading channel, data not available.`

```

**Comment by ktbyers** [comment] 2021-01-15 20:18
@dasiimwe You should open a new issue (or better would be a Netmiko Github discussion question).

Regards, Kirk

**Comment by dasiimwe** [comment] 2021-01-18 00:45
@ktbyers, Thanks for the quick response. Will do.

Meanwhile, i found a work around for this. Junos has a hidden command 'plain-text-password-value' that allows you to enter the password on the same line and avoid the password prompt.

source: [https://www.reddit.com/r/networking/comments/9ptwte/python_and_junos/](url)
