### ISSUE TITLE
ssh key can`t authorized

### ISSUE THREAD

**Issue by FkyMouse** [ktbyers/netmiko#3061] opened 2022-12-22 07:26 UTC
ssh-keygen -t rsa -b 2048

put public key to router

private key to client
________________________________________________________________________________________

import netmiko
from netmiko import ConnectHandler

key_file = "C:\mikrotik_ssh\id_rsa"

mikrotik_router_1 = {
    "device_type": "mikrotik_routeros",
    "host": "192.168.5.22",
    "username": "Dima",
    'password': None,
    "use_keys": True,
    "key_file": key_file,
}

sshCli = ConnectHandler(**mikrotik_router_1)

output = sshCli.send_command("/interface ethernet print")
print(output)

-----------------------------------output----------------------------------------------
netmiko.exceptions.NetmikoAuthenticationException: Authentication to device failed.

Common causes of this problem are:
1. Invalid username and password
2. Incorrect SSH-key file
3. Connecting to the wrong device

Device settings: mikrotik_routeros 192.168.5.22:22
private key file is encrypted

**Comment by ktbyers** [comment] 2022-12-23 08:40
@FkyMouse Have you verified the SSH key works outside of netmiko? Have you looked at the debug log for more details on what is going on?

**Comment by shaspen** [comment] 2022-12-23 19:27
@FkyMouse 
The problem is with directory stinrg you provided for key_file in Windows. because in Python string \ interpretes as Escape character.

the easiest work around is to change the directory to this:
key_file = "C:\\mikrotik_ssh\\id_rsa"

or using raw string:
key_file = r"C:\mikrotik_ssh\id_rsa"

**Comment by ktbyers** [comment] 2022-12-24 07:40
I don't think any of the backslash characters matter here:

```
>>> key_file = "C:\mikrotik_ssh\id_rsa"
>>> key_file2 = r"C:\mikrotik_ssh\id_rsa"
>>> key_file
'C:\\mikrotik_ssh\\id_rsa'
>>> key_file2
'C:\\mikrotik_ssh\\id_rsa'
>>> key_file2 == key_file
True
```

**Comment by FkyMouse** [comment] 2022-12-24 15:30
sorry but i don`t understand what you mean "verified the SSH key.."

**Comment by ktbyers** [comment] 2022-12-24 20:28
@FkyMouse Have you verified the SSH key works outside of Netmiko (if possible)?

**Comment by kacem-expereo** [comment] 2022-12-30 12:28
@FkyMouse  try this from your console
`ssh -i C:\mikrotik_ssh\id_rsa Dima@192.168.5.22`
If you are logged in without the need to input the password then we can assume your "SSH key" is "verified".

**Comment by ktbyers** [comment] 2023-01-26 03:21
@FkyMouse Any update on whether your SSH key works properly outside of Netmiko?

**Comment by ktbyers** [comment] 2023-02-01 04:42
Going to close this as there was no verification that the SSH key is working properly (outside of Netmiko).

**Closed by ktbyers** 2023-02-01 04:42 UTC
