### ISSUE TITLE
ValueError: Router prompt not found: User: in Cisco WLC 'global_delay_factor': 4

### ISSUE THREAD

**Issue by prince07** [ktbyers/netmiko#558] opened 2017-08-24 07:34 UTC
ValueError: Router prompt not found: User: in Cisco WLC 'global_delay_factor': 4 I tryed upto 15,

```
from netmiko import ConnectHandler

def iphelper_add(ip):
    device = {
        'device_type': 'cisco_wlc',
        'ip': ip,
        'username':"user",
        'password':"pass",
        'global_delay_factor': 4,
    }

    net_connect = ConnectHandler(**device)
```

**Comment by ktbyers** [comment] 2017-08-26 01:02
@prince07 Can you post your exception message that you get?

**Comment by whitej6** [comment] 2017-10-16 17:05
I get the same issue with WLCs that are on newer code versions.  Below is the exception message I received.


Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wlcDiscovery.py", line 36, in threadedFunction
    connection = netmiko.ConnectHandler
(ip=device,device_type='cisco_wlc',username=username,password=password,global_delay_factor=10)
  File "/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 131, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 151, in __init__
    self.session_preparation()
  File "/usr/lib/python2.7/site-packages/netmiko/cisco/cisco_wlc_ssh.py", line 103, in session_preparation
    self.set_base_prompt()
  File "/usr/lib/python2.7/site-packages/netmiko/base_connection.py", line 647, in set_base_prompt
    raise ValueError("Router prompt not found: {0}".format(prompt))
ValueError: Router prompt not found: User:

**Comment by ktbyers** [comment] 2017-10-23 20:59
@whitej6 Can you show me what an entire SSH Cli session looks like including username and password prompts and any banners.

You can obfuscate any username/passwords.


Thanks,

Kirk

**Comment by whitej6** [comment] 2017-10-23 21:09
Issue caused by WLC not handling auth fail properly. Not a netmiko issue but the way WLC handles auth fail. Account because locked before running WLC script. Sorry for not updating my response when I located the issue.

**Comment by ktbyers** [comment] 2017-10-23 21:10
No worries...I assume I can close this issue then?

**Comment by mrkcmo** [comment] 2017-10-23 21:18
Hey Kirk,

              Wanted to let you know I subscribed to your website mailing list and never got the confirmation email. I think your sendmail might be not working. Wanted to let you know!

Chris

**Comment by whitej6** [comment] 2017-10-23 21:31
Yessir.

**Comment by ktbyers** [comment] 2017-10-27 01:59
@mrkcmo That is usually due to spam filters on your side (i.e. the message gets blocked or put in the spam folder and you never receive it).

If you can send me your email address, I can check.

**Closed by ktbyers** 2017-10-27 01:59 UTC
