### ISSUE TITLE
loading ntc templates installed via pip fails with "IsADirectoryError"

### ISSUE THREAD

**Issue by 991jo** [ktbyers/netmiko#2073] opened 2020-12-14 21:21 UTC
Hello

when I am using textfsm installed via pip I get this error:

```
Traceback (most recent call last):
  File "/home/jo/foo/netmiko-bug/test.py", line 4, in <module>
    print(router.send_command("show int desc", use_textfsm=True))
  File "/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/netmiko/utilities.py", line 429, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/netmiko/base_connection.py", line 1538, in send_command
    structured_output = get_structured_data(
  File "/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/netmiko/utilities.py", line 340, in get_structured_data
    template_dir = get_template_dir()
  File "/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/netmiko/utilities.py", line 277, in get_template_dir
    with importresources_path(
  File "/usr/lib/foo/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 995, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/ntc_templates/templates'
```

Environment is:
Python 3.9.0
netmiko 3.3.2
ntc-templates 1.6.0
textfsm 1.1.0
venv installed via
```
python3 -m venv .
source bin/activate
pip install netmiko ntc_templates
```

The templates and the index file are in `/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/ntc_templates/templates` as expected. Setting the `NET_TEXTFSM` environment variable to this path works as expected.

the script I run is this:

```
from netmiko import Netmiko

router = Netmiko(host="router.example.com", username="admin", password="somepass", secret="somesecret", device_type="cisco_xr")
print(router.send_command("show int desc", use_textfsm=True))
```

**Comment by ktbyers** [comment] 2021-04-26 04:26
Are you still seeing this issue?

**Comment by 991jo** [comment] 2021-05-01 09:26
I will try find some time to try it again over the weekend.

**Comment by ktbyers** [comment] 2021-05-01 14:10
I tried to reproduce, but I didn't see any issue using either ntc-templates 1.6.0 or ntc-templates 2.0.0 (I was using the Netmiko environment variable). This was only using ntc-templates via PIP and no environment variable / no ntc-templates in my home directory.

I had someone else report a similar issue on Windows, however.

**Comment by ktbyers** [comment] 2021-06-19 17:47
Fixed in this PR:

https://github.com/ktbyers/netmiko/pull/2274

This was a Python 3.9 issue/change.

**Closed by ktbyers** 2021-06-19 17:47 UTC

**Comment by cdleonard** [comment] 2022-02-08 06:54
As far as I can tell this still affects the latest release so it's not possible to use python3.9 + netmiko + ntc_templates.

Can we get a new release with this fix?

**Comment by ktbyers** [comment] 2022-02-08 16:45
@cdleonard Just install the `develop` branch. That should fix the issue.

There probably will be a new release in a month or so, but it depends on some other things (i.e. a NAPALM release).

**Comment by zhajili91** [comment] 2022-03-04 14:26
Hello, @ktbyers ,

I have just tried using netmiko with textFsm and I received this output.

```
Traceback (most recent call last):
  File "/home/jo/foo/netmiko-bug/test.py", line 4, in <module>
    print(router.send_command("show int desc", use_textfsm=True))
  File "/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/netmiko/utilities.py", line 429, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/netmiko/base_connection.py", line 1538, in send_command
    structured_output = get_structured_data(
  File "/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/netmiko/utilities.py", line 340, in get_structured_data
    template_dir = get_template_dir()
  File "/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/netmiko/utilities.py", line 277, in get_template_dir
    with importresources_path(
  File "/usr/lib/foo/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 995, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/ntc_templates/templates'

```
export NET_TEXTFSM=/path/to/ntc-templates/templates/
zhajili@dhcp-10-61-97-83:~/Desktop/Python/Book for Network Engineers/general /chapter18$ echo $NET_TEXTFSM
/path/to/ntc-templates/templates/
I have following 

netmiko            4.0.0a4
Python 3.9.10
ntc-templates      3.0.0

Could you please help ?

**Comment by ktbyers** [comment] 2022-03-04 18:18
@zhajili91 It looks like your Netmiko develop branch is not right or is out of date. I would probably build a new virtual environment from scratch.

Your error here:

```python
 File "/home/jo/foo/netmiko-bug/lib/python3.9/site-packages/netmiko/utilities.py", line 277, in get_template_dir
    with importresources_path(
```

Refers to line 277 in Netmiko's utilities.py, but line 277 is `develop` branch is not that.

https://github.com/ktbyers/netmiko/blob/develop/netmiko/utilities.py#L277


Regards, Kirk

**Comment by zhajili91** [comment] 2022-03-04 19:15
Hello, @ktbyers ,

I did set up from scratch for a virtual environment based on your link again.

https://pynet.twb-tech.com/blog/netmiko-and-textfsm.html

But unfortunately received the same error.

My environment variable is like below.

(.venv) zhajili@dhcp-10-61-97-83:~/Desktop/Python/Book for Network Engineers/TextFSM$ echo $NET_TEXTFSM
/Users/zhajili/Desktop/Python/Book for Network Engineers/TextFSM/ntc-templates/ntc_templates/templates/

Sorry for the dumb question, I have cloned **ntc-template** directly to the TextFSM folder located on the desktop and set the path on the environment variable .
You mentioned that your _develop_ branch is not right, but how can I double-check it? Because I only install netmiko with 
pip install git+https://github.com/ktbyers/netmiko.git@develop command, which I assume it takes the latest branch from GitHub? 

Thank you in advance and appreciate your help

**Comment by ktbyers** [comment] 2022-03-04 21:05
It should have this latest commit (dated Mar 3, 2022). You should be able to check that is there (either by looking at `git log` or by just checking the source code of one of the files that was modified.

https://github.com/ktbyers/netmiko/commits/develop

**Comment by zhajili91** [comment] 2022-03-04 22:27
@ktbyers , thanks a lot, issue was resolved after installing the latest netmiko version as you stated, in my venv it was not showing the latest one, appreciate your help and wish you a nice weekend ahead! :)
