### ISSUE TITLE
Sometimes get error

### ISSUE THREAD

**Issue by fixlensmith** [ktbyers/netmiko#883] opened 2018-07-20 08:35 UTC
Hi i want to ask, sometimes i got error like this, and need to try again until success, sometimes i must manually login first to device

Exception: Error reading SSH protocol banner
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 2044, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
    buf += self._read_timeout(timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/packet.py", line 555, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 1893, in run
    self._check_banner()
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 2049, in _check_banner
    'Error reading SSH protocol banner' + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 2044, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/packet.py", line 353, in readline
    buf += self._read_timeout(timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/packet.py", line 555, in _read_timeout
    raise socket.timeout()
socket.timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/show", line 24, in <module>
    joanna.command(target, parameter)
  File "/usr/lib64/python3.6/joanna.py", line 249, in command
    net_connect = Netmiko(**device)
  File "/usr/lib/python3.6/site-packages/netmiko/ssh_dispatcher.py", line 178, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 207, in __init__
    self.establish_connection()
  File "/usr/lib/python3.6/site-packages/netmiko/base_connection.py", line 689, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/lib/python3.6/site-packages/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 545, in start_client
    raise e
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 1893, in run
    self._check_banner()
  File "/usr/lib/python3.6/site-packages/paramiko/transport.py", line 2049, in _check_banner
    'Error reading SSH protocol banner' + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

**Comment by ChristopherJHart** [comment] 2018-07-20 12:32
What specific device are you encountering this issue with? Are you encountering this issue with any other devices? If not, how many of these devices are you SSHing into using Netmiko? Are all of the devices encountering this issue, or only a specific few?

Judging by the tracebacks, this might be an issue specific to the Paramiko library that is a dependency for Netmiko. We'll need a bit more information to track down exactly what is going wrong.

**Comment by fixlensmith** [comment] 2018-07-20 13:14
my device is cisco , and looping for 10 devices..
and i use jumper host for accessing this devices, i already modify my ssh config files with this requirement..
and as my experiences, i got this error when my connection is little bit slow..

**Comment by ChristopherJHart** [comment] 2018-07-20 13:22
It sounds like the issue is intermittent. Have you tried playing with the `global_delay_factor` value at all to compensate for the possibility of your connection being slow? @ktbyers [wrote an excellent article](https://pynet.twb-tech.com/blog/automation/netmiko-what-is-done.html) yesterday about what the `global_delay_factor` value does and how it can work with slow connections.

**Comment by fixlensmith** [comment] 2018-07-20 15:12
thanks , i will try that..
but if my connection is faster, and i still have global_delay_factor in my script, it will slow down the process right?

**Comment by ChristopherJHart** [comment] 2018-07-20 18:05
Correct - if `global_delay_factor` is increased, then the amount of the time that your entire script takes will increase as well. This is because the `global_delay_factor` value effectively tells Netmiko how much it should slow down all of its processing.

On second thought, I don't think that your specific issue will be resolved by increasing the `global_delay_factor` value. As I mentioned before, your particular traceback is entirely Paramiko-based; Netmiko doesn't throw any exceptions there at all. On closer inspection, this is because Paramiko is having issues connecting to the device. The device is responding to the TCP handshake (otherwise, the device could be considered "offline" and Netmiko would throw an NetMikoTimeoutException exception) but is having trouble completing the SSH handshake (specifically, when reading the SSH protocol banner.) In other words, Paramiko is declaring that the SSH connection has timed out, not Netmiko.

To resolve this issue, we need to tell Paramiko to increase the amount of time it takes before declaring an SSH connection as timed out. Within Netmiko, we can do this by increasing the `blocking_timeout` key from its default of 8 in the dictionary that contains details regarding your device. Example code is below:
```
from netmiko import ConnectHandler
device = {"device_type": "cisco_ios", "ip": "1.2.3.4", "username": "admin", "password": "cisco!123", "blocking_timeout": "16"}
conn = ConnectHandler(**device)
```
You may need to play around with the value a bit in order to get it reliably working. Let us know how it goes!

**Comment by ktbyers** [comment] 2018-08-09 00:25
It doesn't look like there are further actions need on this issue...if there are just re-open it.

**Closed by ktbyers** 2018-08-09 00:25 UTC

**Comment by TomCos** [comment] 2018-11-07 23:28
In case anyone else comes across this issue, I made a comment in the Paramiko thread about it (https://github.com/paramiko/paramiko/issues/673).  Kirk, looks like you also made an appearance in that one.  If anyone thinks it's worth it, we can always add the banner_timeout variable into the Netmiko dictionary passed to Paramiko.
