### ISSUE TITLE
Running Python 3.7 on Windows 10

### ISSUE THREAD

**Issue by shaheeriqbal** [ktbyers/netmiko#1102] opened 2019-02-24 01:02 UTC
Hey,
 i am complete newbie
i tried installing python 3.7 on my machine.
I am running in to an error why i try to run scripts from Netmiko
can anyways please help?
![netmiko error](https://user-images.githubusercontent.com/35785687/53293655-7bec7d00-379d-11e9-9c8a-278e4cb08e0a.JPG)

**Comment by shaheeriqbal** [comment] 2019-02-24 01:04
i was able to install netmiko using anaconda and github
but i am still running into this issue.
![netmiko install](https://user-images.githubusercontent.com/35785687/53293676-d554ac00-379d-11e9-8397-e44054146d16.JPG)

**Comment by ktbyers** [comment] 2019-02-24 02:54
What is the issue on your second screen shot? The module loads fine?

If you are still getting the Netmiko import error in your IDE, then the Python being used by the IDE is not the same Python that you installed the module into.

**Comment by shaheeriqbal** [comment] 2019-02-24 03:05
Thanks for the reply quick Kirk, i am a complete newbie 
i think i am running into an error when using an IDE?
do you recommend any IDE for windows 10?
which will us the python i installed the module into?
or is there any way of installing the module into IDE?

**Comment by OzNetNerd** [comment] 2019-02-27 10:48
@shaheeriqbal , PyCharm and/or InteliJ (whichever you're using), is a fantastic IDE. I'd stick with it.

In regards to installing Netmiko, take a look at these instructions - https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html

**Comment by carlniger** [comment] 2019-05-30 16:49
I'm going to close this since its not a bug/issue/feature request. Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc!

**Closed by carlniger** 2019-05-30 16:49 UTC
