### ISSUE TITLE
I want to read IPs from .csv format file, enter username and password through rawinput and run the show ip int breif command, get output and print in a text file. Pls check if the script is okay

### ISSUE THREAD

**Issue by nishakashyap04** [ktbyers/netmiko#1209] opened 2019-05-12 23:43 UTC
from netmiko import ConnectHandler
import csv
import getpass

with open('IPFile.csv','rt') as csvfile:
          devices = csv.DictReader(csvfile)
          for loopbackip in devices:
              print("***Executing Script on devices:")
              print("***Script Output:")
              net_connect=ConnectHandler(**loopbackip)
              ssh_username = input("SSH username: ")
              ssh_password = getpass.getpass('SSH Password: ')
              net_connect.enable()
              output=net.connect.send_command("show ip interface breif")
              print(output)

file = open('sh_ip_int_brief.txt', 'rw')
file.write('\n'.join(output))
file.close()

**Comment by carlniger** [comment] 2019-05-13 15:35
You may want to take a look at the provided [examples](https://github.com/ktbyers/netmiko/tree/develop/examples) in the repo, specifically [this](https://github.com/ktbyers/netmiko/blob/develop/examples/show_command/show_command.py) to get you started, then [this](https://github.com/ktbyers/netmiko/blob/develop/examples/connect_multiple_devices/connect_multiple.py) to connect to multiple devices.

I'm going to close this since its not a bug/issue/feature request. Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTQ5MjExNGNlNWIzMmRhOTZmNmZkNDA2Nzk4Y2Q1Y2RkMWNhZGEzM2Y5MjI0NDYxODkzM2M0ODIwYzFkMzVmZGY) where you can find a dedicated netmiko channel for questions/comments/etc.

**Closed by carlniger** 2019-05-13 15:35 UTC

**Comment by nishakashyap04** [comment] 2019-05-13 15:43
Thank You for all your guidance. Will try these out.

**Comment by arazzan** [comment] 2021-09-26 18:54
https://e-booksnetworking.blogspot.com/2020/10/back-up-your-network-devices-with-excel.html?m=0

https://github.com/arazzan/network_backup_with_python

**Comment by arazzan** [comment] 2021-09-26 18:55
https://github.com/arazzan/network_backup_with_python
