### ISSUE TITLE
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable host key)

### ISSUE THREAD

**Issue by DNnate** [ktbyers/netmiko#2627] opened 2022-01-18 01:27 UTC
Hi Kirk, I am trying to connect to TP Link Jetstream, 

This is the debug log

DEBUG:paramiko.transport:starting thread (client mode): 0xb7ee26e0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.8.10
DEBUG:paramiko.transport:Remote version/idstring: 'SSH-2.0-IPSSH-6.6.0'
INFO:paramiko.transport:Connected (version 2.0, client IPSSH-6.6.0)
DEBUG:paramiko.transport:kex follows? False
kex algos: ['diffie-hellman-group1-sha1']
server key: ['ssh-dss']
client encrypt: ['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc']
server encrypt: ['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc']
client mac: ['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96']
server mac: ['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96']
client lang: b''
server lang: b''
client compress: ['none']
server compress: ['none']
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
ERROR:paramiko.transport:Exception: Incompatible ssh peer (no acceptable host key)
Traceback (most recent call last):
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py", line 1945, in run
    self._handler_table[ptype](self, m)
  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py", line 2036, in _negotiate_keys
    self._parse_kex_init(m)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py", line 2206, in _parse_kex_init
    raise SSHException('Incompatible ssh peer (no acceptable host key)')
paramiko.ssh_exception.SSHException: Incompatible ssh peer (no acceptable host key)

**Comment by ktbyers** [comment] 2022-01-18 03:26
Hmmmm, I wonder if it is due to "ssh-dss" not being supported on your system (at the OS level)?

**Comment by DNnate** [comment] 2022-01-18 08:41
I am running windows 10. Is there any way around this?

**Comment by DNnate** [comment] 2022-01-23 18:38
If I run below on terminal, it works: ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -oHostKeyAlgorithms=+ssh-dss -c aes128-cbc 2.2.2.2

How can I get nemiko to do the same for the host?

**Comment by DNnate** [comment] 2022-01-25 23:58
I have now added ssh-dss to  _preferred_keys in transport.py. Now I am getting the EOF error below when using tplink_jetstream device type:

DEBUG:paramiko.transport:starting thread (client mode): 0x6f0e0fd0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.8.10
DEBUG:paramiko.transport:Remote version/idstring: 'SSH-2.0-IPSSH-6.6.0'
INFO:paramiko.transport:Connected (version 2.0, client IPSSH-6.6.0)
DEBUG:paramiko.transport:kex follows? False
kex algos: ['diffie-hellman-group1-sha1']
server key: ['ssh-dss']
client encrypt: ['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc']
server encrypt: ['aes128-cbc', 'aes192-cbc', 'aes256-cbc', 'blowfish-cbc', 'cast128-cbc', '3des-cbc']
client mac: ['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96']
server mac: ['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96']
client lang: b''
server lang: b''
client compress: ['none']
server compress: ['none']
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-dss
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-dss host key for 2.2.2.2: 6e3ca110ab027f73d8aa7e40d0516ef8
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication continues...
DEBUG:paramiko.transport:Methods: ['publickey', 'password']
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:EOF in transport thread

**Comment by ktbyers** [comment] 2022-01-26 02:53
Netmiko does not use the KEX in a SSH config file. You would have to do what you did above with _preferred_keys.

Can you post your Python code? Hard to tell on the above what is the cause of the failure.

**Comment by DNnate** [comment] 2022-01-26 21:48
Hi Kirk, this is my Python Code, Many thanks.

from netmiko.ssh_exception import  NetMikoTimeoutException
from paramiko.ssh_exception import SSHException 
from netmiko.ssh_exception import  AuthenticationException
from netmiko import ConnectHandler
import logging
import paramiko


logging.basicConfig(filename='jetstream.log', level=logging.DEBUG)

ip_address = ['2.2.2.2'] 
iosv_TPLink = [
    {
        'device_type': 'tplink_jetstream',
        'host':  ip ,
        'username': 'admin',
        'password': 'password',
        'secret': 'password'
        
    }
    for ip in ip_address
]

commands = ['show running-config | include tacacs-server']

for device_Jetstream in iosv_TPLink:
    try:
        print ( f'Connecting to: {device_Jetstream["host"]}')      
        with ConnectHandler(**device_Jetstream) as net_connect:
                net_connect.enable()
                net_connect.send_config_set ()
                output = net_connect.send_command('show running-config | include tacacs-server')
    except (AuthenticationException):
        print('Incorrect Username or Password: ')
    except (NetMikoTimeoutException):
        print('Timeout to Device: ' )
    except (EOFError):
        print('End of File while attempting device: ')
    except (SSHException):
        print('SSH issue. Are you sure SSH is enabled: ')
    except Exception as unknown_error:
        print ('Other Error:' + unknown_error)
    else:
        print(output)

**Comment by DNnate** [comment] 2022-01-26 22:05
Traceback (most recent call last):
  File "C:\Users\nnated1\jetstream.py", line 30, in <module>
    with ConnectHandler(**device_Jetstream) as net_connect:
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\ssh_dispatcher.py", line 326, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\tplink\tplink_jetstream.py", line 129, in __init__
    return super().__init__(**kwargs)
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\tplink\tplink_jetstream.py", line 19, in __init__
    return super().__init__(**kwargs)
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 350, in __init__
    self._open()
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 355, in _open
    self.establish_connection()
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\netmiko\base_connection.py", line 988, in establish_connection
    self.remote_conn = self.remote_conn_pre.invoke_shell(
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\client.py", line 463, in invoke_shell
    chan = self._transport.open_session()
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py", line 770, in open_session
    return self.open_channel('session',
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py", line 897, in open_channel
    raise e
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\transport.py", line 1923, in run
    ptype, m = self.packetizer.read_message()
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\packet.py", line 437, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "C:\Users\nnated1\AppData\Local\Programs\Python\Python310\lib\site-packages\paramiko\packet.py", line 283, in read_all
    raise EOFError()
EOFError

**Comment by DNnate** [comment] 2022-01-26 22:07
Without the exception handling, I get the above. With the exception handling, I get  'End of File while attempting device: ' as per code

**Comment by ktbyers** [comment] 2022-01-26 22:28
Looks like Netmiko/Paramiko tries to read from the SSH connection and the connection is dead.

Does the device give you any clues (if you look at the logs on the device)?

**Comment by DNnate** [comment] 2022-01-26 22:37
There is nothing on the tplink device to indicate why this is happening

**Comment by ktbyers** [comment] 2022-01-26 22:53
Netmiko/Paramiko are saying it is the device closing the connection?

**Comment by ktbyers** [comment] 2022-02-27 06:08
@DNnate Did you ever get this working?

**Comment by ktbyers** [comment] 2022-03-02 21:53
I am going to close this as it doesn't look like it is actively being worked on.

**Closed by ktbyers** 2022-03-02 21:53 UTC
