### ISSUE TITLE
Option to skip verify space for SCP function

### ISSUE THREAD

**Issue by TomCos** [ktbyers/netmiko#922] opened 2018-08-16 15:45 UTC
Was wondering the LoE to add an option to skip the verify space function being automatically run when the file_transfer function is called.  Reason being is, a lot of devices (mostly terminal servers I'm seeing) that are backend unix/linux, they mount their temporary filesystems straight from memory, not from a disk.  The verify space is getting false data because the filesystem it's checking is returning all 0's for space available, used, blocks, etc.
Thoughts?

**Comment by ktbyers** [comment] 2018-08-16 18:43
@TomCos Can you show an example? What does 'df -k' show for that file system. I wouldn't think it would matter if it a memory file-system or a disk file-system?

The general process would be to subclass and then implement a new remote_space_available method similar to what was done here:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/juniper/juniper.py#L209-L238


Also here is what is called:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/juniper/juniper.py#L209-L238

**Comment by ktbyers** [comment] 2018-08-21 19:04
Strange...is that actually a proper implementation of a tmpfs (I would have thought it still needed to report its size and space available).

Not that it helps you...

```
df -k
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/xvda1      16382888 4455636  11827008  28% /
devtmpfs          769336      16    769320   1% /dev
tmpfs             786164       0    786164   0% /dev/shm
```

We could probably add some sort of a force option or skip_space_check. Someone has to do the PR on it though.

**Comment by TomCos** [comment] 2018-08-23 21:18
I've opened a ticket with the vendor about how their tmpfs is implemented, I agree it's not correct.  For now, I'll just call the functions directly to avoid the check.  Thanks!

**Comment by ktbyers** [comment] 2018-08-23 21:39
Okay, sounds good. I will just close this as I am not seeing a further action on my part. But re-open if there is more to do.

**Closed by ktbyers** 2018-08-23 21:39 UTC

**Comment by BenjaminHoegh** [comment] 2022-05-19 09:35
what is the status on this?

**Comment by BenjaminHoegh** [comment] 2022-05-19 09:37
what's the status on this? has the option to skip verify space for SCP been implemented yet?

**Comment by ktbyers** [comment] 2022-05-19 16:16
@BenjaminHoegh I don't think this was ever done. The SCP primitives are all there so you could do it yourself.

What is the underlying issue you ran into?

**Comment by BenjaminHoegh** [comment] 2022-05-20 20:09
> @BenjaminHoegh I don't think this was ever done. The SCP primitives are all there so you could do it yourself.
> 
> What is the underlying issue you ran into?

For me the issue is that I do not have permission to use `df` or `/bin/df` on the target server
