### ISSUE TITLE
Telnet Session Closed by find_prompt() after call to is_alive().

### ISSUE THREAD

**Issue by ScottW514** [ktbyers/netmiko#763] opened 2018-03-28 15:51 UTC
When ```is_alive()``` is called to test a telnet connection, it sends '0xFF,0xF1' to the host (telnet 'Interpret as Command' followed by 'NOP').  
The host (in this test case, a Cisco 2911 IOS v15.4(3)M3 ) responds with '0x07' (BELL) and '0x71' (letter 'q').
When ```find_prompt()``` is subsequently called, it sends '0x0a' ('\n').  As the host previously responded to the IAC+NOP with the letter 'q', the letter 'q' is on the command line.  When ```find_prompt()``` sends a '\n', it executes the 'q' command (short for 'quit' on IOS) and the host closes the connection.

**Steps to reproduce:**
1. Establish connection to host via telnet
2. Call ```is_alive()```
3. Call ```find_prompt()```

```console
DEBUG:netmiko:read_channel: q

Traceback (most recent call last):
...
  File ".\miniconda3\lib\site-packages\netmiko\base_connection.py", line 823, in find_prompt
    self.clear_buffer()
  File ".\miniconda3\lib\site-packages\netmiko\base_connection.py", line 828, in clear_buffer
    self.read_channel()
  File ".\miniconda3\lib\site-packages\netmiko\base_connection.py", line 329, in read_channel
    output = self._read_channel()
  File ".\miniconda3\lib\site-packages\netmiko\base_connection.py", line 316, in _read_channel
    output = self.remote_conn.read_very_eager().decode('utf-8', 'ignore')
  File ".\miniconda3\lib\telnetlib.py", line 366, in read_very_eager
    return self.read_very_lazy()
  File ".\miniconda3\lib\telnetlib.py", line 403, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed
```

Wireshark Follow TCP Stream Hex Dump:
```
    0000190D  0a 65 6e 64 0d 0a 0d 0a  74 77 73 73 63 2d 72 74   .end.... twssc-rt
    0000191D  72 23                                              r#
# Netmiko is_alive() sends IAC-NOP
0000006A  ff ff f1                                           ...
# Host responds with 'BELL' and 'q'
    0000191F  07                                                 .
    00001920  71                                                 q
# Netmiko find_prompt() sends '\n'
0000006D  0a                                                 .
    00001921  0d 0a                                              ..
```

This behavior appeared in v2.1.0, after the following change was made in ```is_alive()``` (commit [2a0ce80](https://github.com/ktbyers/netmiko/commit/2a0ce80e2f9e64a495ae5a013ba1d2541c6187c8)):

```patch
--- A/netmiko-2.0.2/netmiko/base_connection.py	Fri Feb  9 12:55:10 2018
+++ B/netmiko-2.1.0/netmiko-2.1.0/netmiko/base_connection.py	Wed Mar  7 10:13:56 2018
@@ -283,7 +283,7 @@
                 # Try sending IAC + NOP (IAC is telnet way of sending command
                 # IAC = Interpret as Command (it comes before the NOP)
                 log.debug("Sending IAC + NOP")
-                self.device.write_channel(telnetlib.IAC + telnetlib.NOP)
+                self.write_channel(telnetlib.IAC + telnetlib.NOP)
                 return True
             except AttributeError:
                 return False
```

Prior to this change, every call to ```is_alive()``` for a telnet connection returned false.

If I change ```self.write_channel(telnetlib.IAC + telnetlib.NOP)``` to ```self.write_channel(' ')```, it works as expected, though this may not be a desired solution.

**Comment by ktbyers** [comment] 2018-03-29 02:14
@ScottW514 Okay, maybe we will just eliminate is_alive() we have had ongoing issues making it work for SSH and now telnet.

Writing a space doesn't seem like the correct behavior (for what we should do).

**Comment by ScottW514** [comment] 2018-03-29 12:11
I found the problem.  It's in telnetlib.py:

```python
   def write(self, buffer):
        """Write a string to the socket, doubling any IAC characters.
        Can block if the connection is blocked.  May raise
        socket.error if the connection is closed.
        """
        if IAC in buffer:
            buffer = buffer.replace(IAC, IAC+IAC)
        self.msg("send %r", buffer)
        self.sock.sendall(buffer)
```

The ```write()``` function doubles any IAC characters, which has the effect of escaping it.

Proper IAC + NOP sequence:
```
    00000006  74 77 73 73 63 2d 72 74  72 23                     twssc-rt r#
# Send IAC + NOP
00000004  ff f1                                              ..
# No response from host
# Send newline
00000006  0a                                              ..
# Normal response from host
    00000010  0d 0a                                              ..
    00000012  74 77 73 73 63 2d 72 74  72 23                     twssc-rt r#
```

A possible option would be to extend the Telnet class and override the ```write()``` method with an extra optional argument to disable the IAC escapement when deliberately trying to send a command sequence.

If you concur, I can code/test and submit a pull request.

I'd like it if you kept the ```is_alive()``` function 'alive' as I've come to find it a useful feature.

**Comment by ktbyers** [comment] 2018-03-29 14:44
@ScottW514 Nice work.

Did you see any reason that the telnetlib library did this?

**Comment by ScottW514** [comment] 2018-03-29 15:51
I can't find any documentation that gives a clear answer.  My best guess is that the ```write()``` method is intended to deliberately hide the underlying protocol.

By escaping the IAC characters, they prevent users from breaking/interfering with the connection by unintentionally sending protocol control commands.  None of the other methods provide a mechanism for a user to send commands of their own, leaving all control responsibility to the class.

I think we should be ok if we circumvent this only in the case that we want to send a NOP as the NOP is benign, and any unexpected control response from the host would still be properly processed by the class read methods.

**Comment by ktbyers** [comment] 2018-03-29 17:53
Maybe for the is_alive method, we just handle sending the IAC + NOP ourselves. In other words, do something like:

```
self.sock.sendall(IAC + NOP)
```

And replace self with whatever our reference to the telnetlib object is.

**Comment by ScottW514** [comment] 2018-03-29 18:06
I gave this a go:

```python
self.remote_conn.sock.sendall(telnetlib.IAC + telnetlib.NOP)
```

Works as expected.

**Comment by ktbyers** [comment] 2018-04-02 23:04
Okay, nice.

**Comment by KalleDK** [comment] 2018-04-29 12:36
Just found this as well :)
Though I would have used get_socket, to keep the interface.

`self.remote_conn.get_socket().sendall(telnetlib.IAC + telnetlib.NOP)`

**Comment by ktbyers** [comment] 2018-09-15 05:05
https://github.com/ktbyers/netmiko/pull/953

I merged this here...is_alive() still doesn't work in the way it was intended both for telnet and for SSH so I am still inclined to deprecate and remove it.

I am open to hearing what people use it for though (given that it doesn't really work). I discuss this a bit in the PR and we have ran into ongoing issues with it for SSH.

**Closed by ktbyers** 2018-09-15 05:05 UTC
Labels: Investigate
