### ISSUE TITLE
Enhance the commit() method for IOS-XR

### ISSUE THREAD

**Issue by plucena24** [ktbyers/netmiko#89] opened 2015-05-05 19:19 UTC
- Entering config mode is not necesary to commit. The only way you can commit is if you are already in config mode

line 20
```python
         # Enter config mode (if necessary)
        output = self.config_mode()
```

Add support for:

- commit label
- commit comment
- commit replace
- commit confirmed

**Comment by ktbyers** [comment] 2015-05-18 18:27
I am going to use this as a general placeholder for design spec for IOS-XR commit method.

**Comment by ktbyers** [comment] 2015-05-18 18:51
Design specifications:

1. Do not enter config mode upon commit(), you will already be in commit mode.
2. Handle the exit_config_mode which is going to prompt you about uncommitted changes.

'commit': commit the config
'commit comment': commit with a comment
'commit confirmed <seconds>':  
'commit label <label_name>'
'commit replace'  >>> loading an entirely new config...pretty dangerous I might have this as a completely separate method or not implement. Someone could still manually invoke via send_command

**Comment by ktbyers** [comment] 2015-05-21 23:40
See also issue #88

**Comment by ktbyers** [comment] 2015-05-21 23:41
Additional notes from Pablo:

commit                      [I want to see what the router prints to the screen when this happens]
 
​What comes up depends on whether you have logging enabled or not. Look at the difference:

with logging:

RP/0/0/CPU0:XRv-1(config)#router isis 1
RP/0/0/CPU0:XRv-1(config-isis)#is-type level-2
RP/0/0/CPU0:XRv-1(config-isis)#commit
Wed May 20 12:43:30.200 UTC
RP/0/0/CPU0:May 20 12:43:30.620 : isis[1006]: %ROUTING-ISIS-6-INFO_STARTUP_START : Cold controlled start beginning 
RP/0/0/CPU0:May 20 12:43:34.390 : config[65808]: %MGBL-CONFIG-6-DB_COMMIT : Configuration committed by user 'admin'. Use 'show configuration commit changes 1000000039' to view the changes. 
RP/0/0/CPU0:XRv-1(config-isis)#RP/0/0/CPU0:May 20 12:43:40.819 : isis[1006]: %ROUTING-ISIS-6-INFO_STARTUP_FINISH : Cold controlled start completed 


with no logging:

RP/0/0/CPU0:XRv-1(config)#router ospf 1
RP/0/0/CPU0:XRv-1(config-ospf)#area 0
RP/0/0/CPU0:XRv-1(config-ospf-ar)#commit
Wed May 20 12:44:30.306 UTC
RP/0/0/CPU0:XRv-1(config-ospf-ar)#

If you commit something that doesn't make sense, this is what happens...it fails. In this case, this commit failed because I already have a router bgp 100 process.

RP/0/0/CPU0:XRv-1(config)#router bgp 200
RP/0/0/CPU0:XRv-1(config-bgp)#commit
Wed May 20 12:45:17.213 UTC

% Failed to commit one or more configuration items during a pseudo-atomic operation. All changes made have been reverted. Please issue 'show configuration failed [inheritance]' from this session to view the errors
RP/0/0/CPU0:XRv-1(config-bgp)#


RP/0/0/CPU0:XRv-1(config-bgp)#show configuration failed
Wed May 20 12:45:59.180 UTC
!! SEMANTIC ERRORS: This configuration was rejected by 
!! the system due to semantic errors. The individual 
!! errors with each failed configuration command can be 
!! found below.


router bgp 200
!!% The instance name is used already: asn 0.100 inst-name default
!
end

RP/0/0/CPU0:XRv-1(config-bgp)#


commit label ?          [i.e. I want to see what the options are for commit label]

RP/0/0/CPU0:XRv-1(config)#commit label ?
  WORD  Label for this commit (must begin with an alphabet) 


RP/0/0/CPU0:XRv-1(config)#commit label TEST_LABEL ?
  comment       Assign a comment to this commit
  confirmed     Rollback this commit unless there is a confirming commit
  save-running  Save running configuration to a file
  show-error    Displays commit failures immediately
  <cr>          Commit the configuration changes via pseudo-atomic operation


commit label             [I want to see what the router prints to the screen when this happens]

with logging:

RP/0/0/CPU0:XRv-1(config)#router isis 101        
RP/0/0/CPU0:XRv-1(config-isis)#commit label TEST_LABEL_101
Wed May 20 12:48:30.810 UTC
RP/0/0/CPU0:May 20 12:48:30.989 : isis[1008]: %ROUTING-ISIS-6-INFO_STARTUP_START : Cold controlled start beginning 
RP/0/0/CPU0:May 20 12:48:34.909 : config[65808]: %MGBL-CONFIG-6-DB_COMMIT : Configuration committed by user 'admin'. Use 'show configuration commit changes 1000000044' to view the changes. 


with no logging:

RP/0/0/CPU0:XRv-1(config)#router isis 100
RP/0/0/CPU0:XRv-1(config-isis)#commit label TEST_LABEL
Wed May 20 12:47:52.682 UTC
RP/0/0/CPU0:XRv-1(config-isis)# 


commit confirmed 300 ?     [i.e. I want to see what the options are for commit confirmed]

​There are no options besides just the time.​

​RP/0/0/CPU0:XRv-1(config-isis)#commit confirmed 300 ?
  <cr>  Commit the configuration changes to running


commit confirmed 300   [I want to see what the router prints to the screen when this happens]

with logging:

RP/0/0/CPU0:XRv-1(config-isis)#commit confirmed 300 
Wed May 20 12:50:01.533 UTC
RP/0/0/CPU0:May 20 12:50:01.723 : isis[1009]: %ROUTING-ISIS-6-INFO_STARTUP_START : Cold controlled start beginning 
RP/0/0/CPU0:May 20 12:50:05.643 : config[65808]: %MGBL-CONFIG-6-DB_COMMIT : Configuration committed by user 'admin'. Use 'show configuration commit changes 1000000045' to view the changes. 


with no logging:

RP/0/0/CPU0:XRv-1(config)#router isis 203
RP/0/0/CPU0:XRv-1(config-isis)#commit confirmed 300 
Wed May 20 12:51:51.076 UTC
RP/0/0/CPU0:XRv-1(config-isis)#


If you try to exit before you confirm,  this is what happens:

​RP/0/0/CPU0:XRv-1(config-isis)#end  

You are exiting after a 'commit confirm' with an active rollback session.  If you exit the configuration awaiting confirmation will not be confirmed and the router will immediately rollback to the previous configuration.
Do you wish to exit? [no]: ​


You can then confirm your commit by commiting again:

RP/0/0/CPU0:XRv-1(config)#commit 
Wed May 20 12:51:10.319 UTC

% Confirming commit for trial session.


commit comment some comment      [I want to see what the router prints to the screen when this happens]

with logging:

RP/0/0/CPU0:XRv-1(config)#router isis 205
RP/0/0/CPU0:XRv-1(config-isis)#commit comment MY_COMMENT_206
Wed May 20 12:54:43.384 UTC
RP/0/0/CPU0:May 20 12:54:43.454 : config[65808]: %MGBL-CONFIG-6-DB_COMMIT : Configuration committed by user 'admin'. Use 'show configuration commit changes 1000000051' to view the changes. 
RP/0/0/CPU0:XRv-1(config-isis)#

without logging:
 
RP/0/0/CPU0:XRv-1(config)#router isis 205 
RP/0/0/CPU0:XRv-1(config-isis)#commit comment MY_COMMENT_205
Wed May 20 12:53:42.948 UTC
RP/0/0/CPU0:XRv-1(config-isis)#


Also where does the label show up?

RP/0/0/CPU0:XRv-1#show configuration commit list 
Wed May 20 12:55:29.321 UTC
SNo. Label/ID    User      Line                Client      Time Stamp
~~~~ ~~~~~~~~    ~~~~      ~~~~                ~~~~~~      ~~~~~~~~~~
1    1000000051  admin     con0_0_CPU0         CLI         Wed May 20 12:54:43 2015
2    1000000050  admin     con0_0_CPU0         CLI         Wed May 20 12:54:18 2015
3    1000000049  admin     con0_0_CPU0         CLI         Wed May 20 12:53:42 2015
4    1000000048  admin     con0_0_CPU0         CLI         Wed May 20 12:53:27 2015
5    1000000047  admin     con0_0_CPU0         CLI         Wed May 20 12:51:51 2015
6    1000000046  admin     con0_0_CPU0         CLI         Wed May 20 12:51:38 2015
7    1000000045  admin     con0_0_CPU0         CLI         Wed May 20 12:50:01 2015
8    TEST_LABEL  admin     con0_0_CPU0         CLI         Wed May 20 12:48:30 2015
9    1000000043  admin     con0_0_CPU0         CLI         Wed May 20 12:48:18 2015
10   TEST_LABEL  admin     con0_0_CPU0         CLI         Wed May 20 12:47:52 2015
11   1000000041  admin     con0_0_CPU0         CLI         Wed May 20 12:44:30 2015
12   1000000040  admin     con0_0_CPU0         CLI         Wed May 20 12:44:20 2015
13   1000000039  admin     con0_0_CPU0         CLI         Wed May 20 12:43:30 2015
14   1000000038  admin     con0_0_CPU0         CLI         Wed May 20 12:43:13 2015
15   1000000037  admin     con0_0_CPU0         CLI         Wed May 20 12:42:58 2015
16   1000000036  admin     con0_0_CPU0         CLI         Tue May  5 18:48:17 2015
17   1000000035  admin     con0_0_CPU0         CLI         Tue May  5 17:16:59 2015 


Or to get a more detailed view (and be able to see the comments) you can look at a details output:


RP/0/0/CPU0:XRv-1#show configuration commit list detail 
Wed May 20 12:55:40.090 UTC

   1) CommitId: 1000000051                 Label: NONE
      UserId:   admin                      Line:  con0_0_CPU0
      Client:   CLI                        Time:  Wed May 20 12:54:43 2015
      Comment:   MY_COMMENT_206 

   2) CommitId: 1000000050                 Label: NONE
      UserId:   admin                      Line:  con0_0_CPU0
      Client:   CLI                        Time:  Wed May 20 12:54:18 2015
      Comment:  NONE

   3) CommitId: 1000000049                 Label: NONE
      UserId:   admin                      Line:  con0_0_CPU0
      Client:   CLI                        Time:  Wed May 20 12:53:42 2015
      Comment:   MY_COMMENT_205 

   4) CommitId: 1000000048                 Label: NONE
      UserId:   admin                      Line:  con0_0_CPU0
      Client:   CLI                        Time:  Wed May 20 12:53:27 2015
      Comment:   MY_COMMENT  

   5) CommitId: 1000000047                 Label: NONE
      UserId:   admin                      Line:  con0_0_CPU0
      Client:   CLI                        Time:  Wed May 20 12:51:51 2015
      Comment:  NONE


And how do you do a rollback and how can you use the label in the rollback?

RP/0/0/CPU0:XRv-1#rollback configuration ?              
  last  Rollback last <n> commits made
  to    Rollback up to (and including) a specific commit 

RP/0/0/CPU0:XRv-1#rollback configuration to ?
  HELLO           1000000028
  TEST_LABEL      1000000042
  TEST_LABEL_101  1000000044
  1000000051      Commit ID
  1000000050      Commit ID
  1000000049      Commit ID
  1000000048      Commit ID
  1000000047      Commit ID
  1000000046      Commit ID
  1000000045      Commit ID
  1000000044      Commit ID 

RP/0/0/CPU0:XRv-1#rollback configuration to HELLO ?
  best-effort  Rollback via best-effort operation
  comment      Assign a comment to this rollback
  force        Override commit blocks
  label        Assign a label to this rollback
  <cr>         

RP/0/0/CPU0:XRv-1#rollback configuration to HELLO 
Wed May 20 12:59:05.496 UTC
Loading Rollback Changes.
Loaded Rollback Changes in 1 sec 
Committing.RP/0/0/CPU0:May 20 12:59:06.586 : ipv4_arm[265]: %IP-IP_ARM-6-CFLCT_NO_LONGER : The IPv4 address 1.1.1.1/32 on Loopback100 is no longer forced down due to IPv4 address conflicts 

33 items committed in 1 sec (32)items/sec
Updating.
Updated Commit database in 1 sec 
Configuration successfully rolled back to 'HELLO'.


Or you can do this:


RP/0/0/CPU0:XRv-1(config)#load rollback changes ?
  HELLO           1000000028
  TEST_LABEL      1000000042
  TEST_LABEL_101  1000000044
  last            Changes for rolling back last <n> commits
  to              Changes up to (and including) a specific commit
  1000000051      Commit ID
  1000000050      Commit ID
  1000000049      Commit ID
  1000000048      Commit ID
  1000000047      Commit ID
  1000000046      Commit ID

RP/0/0/CPU0:XRv-1(config)#load rollback changes TEST_LABEL 
Building configuration...
Loading.
54 bytes parsed in 1 sec (52)bytes/sec



then once they are loaded, you can look at them while they are "staged"

RP/0/0/CPU0:XRv-1(config)#show configuration 
Wed May 20 13:00:38.630 UTC
Building configuration...
!! IOS XR Configuration 5.1.2
no router isis 100
end

Then if you are happy with them, you can commit:


RP/0/0/CPU0:XRv-1(config)#commit
Wed May 20 12:59:50.193 UTC
RP/0/0/CPU0:XRv-1(config)#

**Comment by ktbyers** [comment] 2015-05-22 02:09
@plucena24  (Pablo see my '# valid command' questions below?

From the above, here are the proposed CLI config commands to send:

commit
commit confirmed <time>
commit label <LABEL>
commit label <LABEL> confirmed <time>
commit label <LABEL> comment "the comment string"
commit label <LABEL> comment "the comment string" confirmed <time>     # valid command?
commit comment "the comment string"
commit comment "the comment string" confirmed <time>                             # valid command?

I will key errors off of "failed to commit". commit will be assumed successful unless that message appears after commit.

Trying to exit config with uncommitted changes will cause changes to be discarded and raise an exception.
Trying to exit config after commit confirmed will cause changes to be discarded and raise an exception.

Will exit configuration mode after successful commit.

**Comment by plucena24** [comment] 2015-05-22 14:11
commit label comment "the comment string" confirmed # valid command?

No, this is not valid. What you do is this:
RP/0/0/CPU0:XR1(config-if)#
RP/0/0/CPU0:XR1(config-if)#commit confirmed 300
Fri May 22 14:09:33.753 UTC
RP/0/0/CPU0:XR1(config-if)#commit label LABEL comment COMMENT
Fri May 22 14:09:46.352 UTC

% Confirming commit for trial session.


Or you can do this:

RP/0/0/CPU0:XR1(config)#commit label LABEL1 confirmed
Fri May 22 14:10:39.919 UTC
RP/0/0/CPU0:XR1(config)#commit comment COMMENT1
Fri May 22 14:10:58.797 UTC

% Confirming commit for trial session.



On Thu, May 21, 2015 at 10:09 PM, Kirk Byers <notifications@github.com>
wrote:

> @plucena24 <https://github.com/plucena24> (Pablo see my '# valid command'
> questions below?
>
> From the above, here are the proposed CLI config commands to send:
>
> commit
> commit confirmed
> commit label
> commit label confirmed
> commit label comment "the comment string"
> commit label comment "the comment string" confirmed # valid command?
> commit comment "the comment string"
> commit comment "the comment string" confirmed # valid command?
>
> I will key errors off of "failed to commit". commit will be assumed
> successful unless that message appears after commit.
>
> Trying to exit config with uncommitted changes will cause changes to be
> discarded and raise an exception.
> Trying to exit config after commit confirmed will cause changes to be
> discarded and raise an exception.
>
> Will exit configuration mode after successful commit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ktbyers/netmiko/issues/89#issuecomment-104475886>.
>



-- 
*Pablo Lucena*

**Comment by ktbyers** [comment] 2015-06-10 21:17
IOS-XR commit support has been added in.

**Closed by ktbyers** 2015-06-10 21:17 UTC
