### ISSUE TITLE
Configure vlan interface ip address to several switch Netmiko

### ISSUE THREAD

**Issue by Dayesindy** [ktbyers/netmiko#1455] opened 2019-11-11 17:27 UTC
I need to configure the IP address to new vlan interface of several switches.

the IP addresses of the new vlan interfaces, are different for each device.
this IPs are in a txt file

I have the following:

#cat IPs_SW_CISCO_TELNET.txt <-- (this are the switch´s IP addresses that I am going to configure )
10.1.0.1
10.2.0.3
10.4.0.1

#cat IPs_NEW_INT_VLAN <-- (this are de IP address of new interface vlan)
10.2.3.1 255.255.255.0
10.2.3.2 255.255.255.0
10.2.4.1 255.255.255.0

**netmiko scrip:**

import netmiko
from netmiko import Netmiko
from netmiko import ConnectHandler
from netmiko.ssh_exception import SSHException
from netmiko.ssh_exception import NetMikoTimeoutException

# Read from a list of hostnames to connect to
hosts = open('IPs_SW_CISCO_TELNET.txt','r')
hosts = hosts.read()
hosts = hosts.strip().splitlines()

ip_int_vlan = open('IPs_NEW_INT_VLAN.txt','r')

# Loop to process hosts in hosts.txt file
for host in hosts:
        switch_cisco_telnet = {
                'device_type': 'cisco_ios_telnet',
                'ip': host, 
                'username': 'username',
                'password': 'password',
        }

        # SSH Connection Handler
        net_connect = ConnectHandler(**switch_cisco_telnet)

        #open file to write command output
        file = open(host + '_output.txt', 'w')

        # Execute command
        config_commands = [ 'interface vlan 10',
                'ip address' + ip_int_vlan',   <---- (I don't know how to make it only take one ip from the txt file)
                'no shutdown',
                'exit',
                'write' ]
        output = net_connect.send_config_set(config_commands)
        net_connect.disconnect()

        # Print output to console screen
        print('-------------- Output from ' + host + '------------------')
        print(output)
        print()
        print()

        # Write output to file above
        file.write(output)
        file.close()

**Comment by carlmontanari** [comment] 2019-11-11 20:40
Going to close this as its not a bug/issue in netmiko - the Slack community is a much better place for things like this. Short answer though is split your `file` arg on line breaks... something like: `list_of_ips = opened_file_thing.splitlines()`.

Feel free to join the Pynet slack community [here](https://join.slack.com/t/pynet/shared_invite/enQtNTA2MDI3NjU0MTM0LTIyZDdhMTBlOWNmNDJhNjkxZTEyMDg3NTRkOWIxMTUwOTAzYmQ0ZjMwMGMyNTM4N2E1YzA3YWQ1MWFiOWM1YzU) where you can find a dedicated netmiko channel for questions/comments/etc if you're still having any issues.

**Closed by carlmontanari** 2019-11-11 20:40 UTC
